# Generated by Django 4.0.4 on 2022-06-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkinLogs',
            new_name='SkinLog',
        ),
    ]
