# Generated by Django 4.0.4 on 2022-06-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0003_alter_skindata_seeds_b_alter_skindata_seeds_g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skindata',
            name='seeds_b',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='skindata',
            name='seeds_g',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='skinlog',
            name='seeds_b',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='skinlog',
            name='seeds_g',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
