# Generated by Django 4.0.4 on 2022-06-02 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0005_remove_skindata_url_remove_skindata_url_stt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='skindata',
            name='urls',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='steam.urls'),
            preserve_default=False,
        ),
    ]
