# Generated by Django 4.0.4 on 2022-06-02 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0006_urls_alter_skindata_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='skindata',
            name='urls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='steam.url'),
        ),
        migrations.DeleteModel(
            name='Urls',
        ),
    ]
