# Generated by Django 4.0.4 on 2022-06-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0007_url_alter_skindata_urls_delete_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
