# Generated by Django 4.0.4 on 2022-06-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0009_alter_skindata_seeds_b_alter_skindata_seeds_g_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skindata',
            old_name='seeds_b',
            new_name='blue',
        ),
        migrations.RenameField(
            model_name='skindata',
            old_name='seeds_g',
            new_name='gold',
        ),
    ]
