# Generated by Django 4.0.4 on 2022-06-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0010_rename_seeds_b_skindata_blue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skinlog',
            old_name='seeds_b',
            new_name='blue',
        ),
        migrations.RenameField(
            model_name='skinlog',
            old_name='seeds_g',
            new_name='gold',
        ),
        migrations.AddField(
            model_name='skindata',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
